### ISSUE TITLE
使用过程中出现的问题

### ISSUE THREAD

**Issue by dayney** [okoala/vue-vuex#3]
使用过程中出现的问题
``` JavaScript
Error: Cannot find module 'babel-runtime/helpers/interop-require'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/study/vue-vuex/node_modules/babel-core/lib/api/node.js:7:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
[nodemon] app crashed - waiting for file changes before starting...

> vue-vuex@0.1.0 copy /study/vue-vuex
> gulp --gulpfile build/gulp/index.js

[13:45:52] Working directory changed to /study/vue-vuex/build/gulp
[13:45:52] Using gulpfile /study/vue-vuex/build/gulp/index.js
[13:45:52] Starting 'default'...
[13:45:52] Finished 'default' after 1.62 ms
/study/vue-vuex/build/webpack/devServer.js:14
  contentBase: `http://${config.get('server_host')}:${config.get('server_port'
               ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

遇到这样的问题怎么解决啊

**Comment by okoala** [comment]
@dayney  bebel-runtime这个模块没有安装好，需要重新安装下.

``` npm install bebel-runtime --verbose  ```

**Comment by dayney** [comment]
你把包名打错了`https://github.com/okoala/vue-vuex/issues/3`

**Comment by dayney** [comment]
***错误提示***
``` 
Error: Cannot find module 'babel-runtime/helpers/interop-require'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
```
没有这个文件`babel-runtime/helpers/interop-require`,只有`_interop-require-default.js`和`_interop-require-wildcard.js`两个文件

**Comment by okoala** [comment]
@dayney  你还是把整个node_modules干掉，重新安装吧，看来是之前没有安装完就被意外中断了。

你可以

```
npm cache clean
npm install --verbose
```

**Comment by lovemyrmb** [comment]
亲, 代码跑起来了,无法访问  http://localhost:4006/index.html 是什么原因

**Comment by wendesun** [comment]
我也是一样的错误 无法访问 http://localhost:4006/index.html

**Comment by wendesun** [comment]
git clone https://github.com/okoala/vue-vuex.git
cd vue-vuex
cnpm install
npm run dev  
 无法访问 http://localhost:4006/index.html

**Comment by leo-lai** [comment]
部署没报错，访问不了 http://localhost:4006/index.html

**Comment by okoala** [comment]
[a71dd1a] windows系统下的问题，现在已经修复
